customhost = "employeenew.crie2ki4ey74.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Sujit1069"
customdb = "employee"
custombucket = "plusemployee"
customregion = "ap-south-1"
